on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: -D errcheck -E gochecknoinits -E godot -E goimports -E gosec -E misspell -E unconvert -E whitespace
