on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: Test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        args: -D errcheck -E gochecknoinits -E godot -E misspell -E unconvert -E whitespace
